### ISSUE TITLE
Fix misleading message

### ISSUE THREAD

**Issue by rakyll** [goiot/devices#11]
README mentions the following:

> These libraries rely on Go's new exp/io interfaces and are designed so they can be used as is or via
> existing Go IoT libraries/frameworks such as GoBot, Embed and hwio.

Even though this is practically possible, this is not the goal of exp/io packages. Trying to achieve it by writing drivers that work against Gobot, Embed, etc also will create confusing and more layers of unnecessary implementation. The more optimal strategy is to rewrite, eg. rewriting Gobot's SPI adaptor layer as an spi.driver and contribute it to golang.org/x/exp/spi.

/cc @mattetti

**Comment by mattetti** [comment]
I realize the issue was that my text wasn't clear. What you are mentioning is what I had in mind. I wanted to mention that these "drivers" can be used/shared between various higher lever projects. I'll remove the text since it's obviously confusing.

**Comment by rakyll** [comment]
It would be nice to write a blog post about this possibility, I am just not sure if it is the first things we should mention.
