### ISSUE TITLE
dotstar: nothing works

### ISSUE THREAD

**Issue by rakyll** [goiot/devices#17]
The examples are not working. We are not setting the bits per word, SPI mode or the max speed. I don't know what else is missing but was not able to light up my dotstar strip.

**Comment by mattetti** [comment]
That is really strange, it works great for me (8 LED strip). Are you sure it's not a connectivity issue? Are you testing on a raspi 3?

**Comment by rakyll** [comment]
If you have you SPI bus configured for other values of spi mode, clock speed and bits per word; it is not working. Once an SPI bus is configured, it uses the last configured values. But for someone, who has just unboxed their raspberry pi or used the spi bus with other settings, this package is not going to work.
